import os
import unicodedata
import re
import argparse  # <-- NEW

# Argument parser for optional character replacement
parser = argparse.ArgumentParser(description="Stitch scripts together with optional character replacement.")
parser.add_argument(
    "--replace-invalid-chars",
    action="store_true",
    default=False,  # Change to True if you want to enable replacement by default
    help="Replace non-ASCII/invalid characters with [INVALID-CHAR]."
)
args = parser.parse_args()

# Hardcoded list of scripts to stitch together
files_to_stitch = [
    "expr_functions.py",
    "main copy.py",
]
output_file = "./output/stitched_code.py"
delimiter = "# ===== FILE: {filename} =====\n"

total_replacements = 0
file_replacements = {}

stitched_contents = []

for fname in files_to_stitch:
    if not os.path.isfile(fname):
        print(f"Warning: {fname} does not exist, skipping.\n")
        continue
    with open(fname, "rb") as infile:
        raw = infile.read()
        text = raw.decode("utf-8", errors="replace")
        text = unicodedata.normalize("NFC", text)

        num_invalid = 0
        if args.replace_invalid_chars:
            # Count and replace both "�" and all non-ASCII characters
            num_invalid = text.count("�")
            non_ascii_matches = re.findall(r'[^\x00-\x7F]', text)
            num_invalid += len(non_ascii_matches)
            total_replacements += num_invalid
            file_replacements[fname] = num_invalid

            # Replace all non-ASCII chars (including "�") with [INVALID-CHAR]
            text = re.sub(r'[^\x00-\x7F]', '[INVALID-CHAR]', text)
            text = text.replace("�", "[INVALID-CHAR]")
        else:
            # Just count occurrences, no replacement
            num_invalid = text.count("�") + len(re.findall(r'[^\x00-\x7F]', text))
            total_replacements += num_invalid
            file_replacements[fname] = num_invalid

        stitched_contents.append((fname, text))

note = (
    "# -----------------------------------------------\n\n"
    + "# @johannesrenz\n"
    + "# -----------------------------------------------\n\n"
    + "# This file was automatically generated by stiching.py\n"
    + "# It stitches together the following scripts:\n"
    + "".join(f"#   - {fname} (replacements: {file_replacements.get(fname, 0)})\n" for fname in files_to_stitch)
    + "# -----------------------------------------------\n\n"
    + (
        "#Some non-compatible characters were replaced with [INVALID-CHAR].\n"
        f"#Total non-UTF8 characters replaced: {total_replacements}\n"
        if args.replace_invalid_chars and total_replacements > 0
        else "# Character replacement was disabled or no non-UTF8 characters found.\n"
    )
    + "# -----------------------------------------------\n\n"
    + '# Note: This file is for reference only. It combines multiple scripts into one. It should run though.\n'
    + "# -----------------------------------------------\n\n"
)

os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, "w", encoding="utf-8") as outfile:
    outfile.write(note)
    for fname, text in stitched_contents:
        outfile.write(delimiter.format(filename=fname))
        outfile.write(text)
        outfile.write("\n\n")

print(f"Stitched {len(stitched_contents)} files into {output_file}")
if args.replace_invalid_chars:
    print(f"Total non-UTF8 characters replaced: {total_replacements}")
if not args.replace_invalid_chars:
    print(f"Total non-UTF8 characters detected: {total_replacements}")
    print("Character replacement was disabled. \n Tex use not advised.")
