"""
@johannesrenz
"""

import os
import unicodedata
import re

# Hardcoded list of scripts to stitch together
files_to_stitch = [
    "expr_functions.py",
    "main copy.py",
]
output_file = "./output/stitched_code.py"
delimiter = "# ===== FILE: {filename} =====\n"

total_replacements = 0
file_replacements = {}

stitched_contents = []

for fname in files_to_stitch:
    if not os.path.isfile(fname):
        print(f"Warning: {fname} does not exist, skipping.\n")
        continue
    with open(fname, "rb") as infile:
        raw = infile.read()
        text = raw.decode("utf-8", errors="replace")
        text = unicodedata.normalize("NFC", text)

        # Count and replace both "�" and all non-ASCII characters
        num_invalid = text.count("�")
        # Count non-ASCII chars (excluding already counted "�")
        non_ascii_matches = re.findall(r'[^\x00-\x7F]', text)
        num_invalid += len(non_ascii_matches)
        total_replacements += num_invalid
        file_replacements[fname] = num_invalid

        # Replace all non-ASCII chars (including "�") with [INVALID-CHAR]
        text = re.sub(r'[^\x00-\x7F]', '[INVALID-CHAR]', text)
        text = text.replace("�", "[INVALID-CHAR]")
        stitched_contents.append((fname, text))

note = (
    "# -----------------------------------------------\n\n"
    + "# @johannesrenz\n"
    + "# -----------------------------------------------\n\n"
    + "# This file was automatically generated by stiching.py\n"
    + "# It stitches together the following scripts:\n"
    + "".join(f"#   - {fname} (replacements: {file_replacements.get(fname, 0)})\n" for fname in files_to_stitch)
    + "# -----------------------------------------------\n\n"
    + (
        "#Some non-compatible characters were replaced with [INVALID-CHAR].\n"
        f"#Total non-UTF8 characters replaced: {total_replacements}\n"
        if total_replacements > 0
        else "# No non-UTF8 characters found in the stitched files.\n"
    )
    + "# -----------------------------------------------\n\n"
    + '# Note: This file is for reference only. It combines multiple scripts into one. It should run though.\n'
    + "# -----------------------------------------------\n\n"
)

with open(output_file, "w", encoding="utf-8") as outfile:
    outfile.write(note)
    for fname, text in stitched_contents:
        outfile.write(delimiter.format(filename=fname))
        outfile.write(text)
        outfile.write("\n\n")

print(f"Stitched {len(stitched_contents)} files into {output_file}")
print(f"Total non-UTF8 characters replaced: {total_replacements}")